### ISSUE TITLE
do you know how to make your own?

### ISSUE THREAD

**Issue by Rahib777-7** [techguy16/nLiteAddons#1]

**Comment by techguy16** [comment]
Yes. I get the EXE, put it in a folder, find the silent install flag, and use VirtualTek's nLite Addon maker.

**Comment by Rahib777-7** [comment]
> Yes. I get the EXE, put it in a folder, find the silent install flag, and use VirtualTek's nLite Addon maker.

virtualttek's nlite addon maker?

**Comment by techguy16** [comment]
win2k+ and linux+wine:
[nlaom21.exe](http://mirror1.filefacts.com/a85989e1de9d078d029c9ce6ff98e3bd/nlaom21.exe)
